sudo: required
language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  - master

# TODO (Karun): This works only if travis has k8s environment. Hence commenting it for now.
#install:
#    - go get -v github.com/onsi/ginkgo/ginkgo
#    - go get -v github.com/onsi/gomega
#    - export PATH=$PATH:$HOME/gopath/bin

# TODO (Karun): This works only if travis has k8s environment. Hence commenting it for now.
# script: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2

services:
  - docker

after_success:
  - docker --version
  - export REPO=quay.io/cnigenie/v1.5
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io/cnigenie/v1.5
  - docker build -t cnigenie -t $REPO:$TAG -f conf/1.5/Dockerfile .
  - docker tag $REPO:$TAG
  - docker tag $REPO:$TRAVIS_BUILD_NUMBER
  - docker push $REPO
